repos:
-   repo: https://github.com/stepanLav/pre-commit-hooks
    rev: 9fccdad888ee53bbdc43cf86e72a513a3792e161
    hooks:
    -   id: check-telenova-config
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
