repos:
-   repo: https://github.com/stepanLav/pre-commit-hooks
    rev: b814fa8ec71abae0dc2c958b8dafc35aa90530f9
    hooks:
    -   id: check-telenova-config
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
